name: Docker Image CI

on:
  push:
    tags: # on two-word codename-tags (e.g. mango-angioplasty, syrupy-containment)
      - '*-*'

jobs:
  build_container:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4

    - id: get-tagname    
      run: |
        export tagname=$(git tag --points-at=HEAD)
        echo "tagname=$tagname" >> $GITHUB_OUTPUT

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.TAGNAME }}
