name: Docker Image CI

on:
  push:
    tags: # on two-word codename-tags (e.g. mango-angioplasty, syrupy-containment)
      - "*-*"

jobs:
  build_container:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN_GHCR }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ocodo/uvxytdlp:${{ github.ref_name }}
