name: Docker Image CI

on:
  push:
    tags: # on two-word codename-tags (e.g. mango-angioplasty, syrupy-containment)
      - "*-*"

jobs:
  build_container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Build and Push
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        tags: |
          ghcr.io/ocodo/uvxytdlp/uvxytdlp-ui:${{ github.ref_name }}
          ghcr.io/ocodo/uvxytdlp/uvxytdlp-ui:latest              
