name: Docker Image CI

on:
  push:
    tags: # on two-word codename-tags (e.g. mango-angioplasty, syrupy-containment)
      - "*-*"

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: https://ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN_GHCR }}
    - name: Build Tag Push to ghcr.io
      run: |
        docker build -t uvxytdlp-ui .
        docker tag uvxytdlp-ui ghcr.io/ocodo/uvxytdlp/uvxytdlp-ui:${{ github.ref_name }}
        docker push ghcr.io/ocodo/uvxytdlp/uvxytdlp-ui:${{ github.ref_name }}
